connection:         propel
package:            plugins.ncPropelChangeLogBehaviorPlugin.lib.model

classes:
  ncChangeLogEntry:
    tableName:      nc_change_log_entry
    columns:
      id:
      class_name:
        type:       varchar(255)
        required:   true
        index:      true
      object_pk:
        type:       varchar(50)
        required:   true
        index:      true
      changes_detail:
        type:       longvarchar
        required:   true
      username:
        type:       varchar(255)
      operation_type:
        type:       tinyint
        required:   true
      created_at:   ~
