connection:         propel
package:            plugins.ncPropelChangeLogBehaviorPlugin.lib.model

classes:
  ncChangeLogEntry:
    tableName:      nc_change_log_entry
    indexes:
      changelog:    [class_name, object_pk]
    columns:
      id:           ~
      class_name:
        type:       varchar(255)
        required:   true
      object_pk:
        type:       varchar(50)
        required:   true
        phpName:    ObjectPK
      changes_detail:
        type:       longvarchar
        required:   true
      username:
        type:       varchar(255)
      operation_type:
        type:       tinyint
        required:   true
      created_at:   ~
    
